name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        buildtags:
          - slicelabels # there's no such tag when this is being written, but it makes the CI job name more obvious.
          - stringlabels
          - dedupelabels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'

      - name: Checkout Repo
        uses: actions/checkout@v2

      # This file would normally be created by `make assets`, here we just
      #  mock it because the file is required for the tests to pass.
      - name: Mock building of necessary react file
        run: mkdir web/ui/static/react && touch web/ui/static/react/index.html

      - name: Run Tests
        run: GO=/usr/local/go/bin/go GOOPTS=-tags=${{ matrix.buildtags }} make common-test